### ISSUE TITLE
botocore.exceptions.ConnectTimeoutError and lots of DEBUG outputs

### ISSUE THREAD

**Issue by scottyhq** [ASFHyP3/hyp3-isce2#176]
### The bug
Running hyp3-isce2 (0.9.2) locally I'm seeing a lot of initial logging messages related to botocore looking for cloud credentials. It looks like there is a traceback related to looking for instance metadata (would only work on AWS), but in any case the code ultimately succeeds successfully.

### To Reproduce
```bash
docker run -it --rm \
    -e EARTHDATA_USERNAME=$EARTHDATA_USERNAME \
    -e EARTHDATA_PASSWORD=$EARTHDATA_PASSWORD \
    -e ESA_USERNAME=$ESA_USERNAME \
    -e ESA_PASSWORD=$ESA_PASSWORD \
    ghcr.io/asfhyp3/hyp3-isce2:0.9.2 \
        ++process insar_tops_burst \
        S1_136231_IW2_20200604T022312_VV_7C85-BURST \
        S1_136231_IW2_20200616T022313_VV_5D11-BURST \
        --looks 20x4 \
        --apply-water-mask False
```

 ### Additional context

```pytb
2024-01-11 03:07:22,367 - botocore.credentials - DEBUG - Looking for credentials via: iam-role
2024-01-11 03:07:22,368 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 169.254.169.254:80
2024-01-11 03:07:23,370 - botocore.utils - DEBUG - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/api/token: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
Traceback (most recent call last):
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out
```

<details>
  <summary>full traceback</summary>

```pytb
/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/hyp3_isce2/__main__.py:40: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  eps = entry_points()['hyp3']
2024-01-11 03:07:22,348 - botocore.hooks - DEBUG - Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2024-01-11 03:07:22,351 - botocore.hooks - DEBUG - Changing event name from before-call.apigateway to before-call.api-gateway
2024-01-11 03:07:22,352 - botocore.hooks - DEBUG - Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2024-01-11 03:07:22,355 - botocore.hooks - DEBUG - Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2024-01-11 03:07:22,356 - botocore.hooks - DEBUG - Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2024-01-11 03:07:22,357 - botocore.hooks - DEBUG - Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2024-01-11 03:07:22,357 - botocore.hooks - DEBUG - Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2024-01-11 03:07:22,359 - botocore.hooks - DEBUG - Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2024-01-11 03:07:22,360 - botocore.hooks - DEBUG - Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2024-01-11 03:07:22,360 - botocore.hooks - DEBUG - Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2024-01-11 03:07:22,360 - botocore.hooks - DEBUG - Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2024-01-11 03:07:22,363 - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2024-01-11 03:07:22,365 - botocore.credentials - DEBUG - Looking for credentials via: env
2024-01-11 03:07:22,365 - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2024-01-11 03:07:22,365 - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2024-01-11 03:07:22,365 - botocore.credentials - DEBUG - Looking for credentials via: sso
2024-01-11 03:07:22,365 - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2024-01-11 03:07:22,365 - botocore.credentials - DEBUG - Looking for credentials via: custom-process
2024-01-11 03:07:22,366 - botocore.credentials - DEBUG - Looking for credentials via: config-file
2024-01-11 03:07:22,366 - botocore.credentials - DEBUG - Looking for credentials via: ec2-credentials-file
2024-01-11 03:07:22,366 - botocore.credentials - DEBUG - Looking for credentials via: boto-config
2024-01-11 03:07:22,366 - botocore.credentials - DEBUG - Looking for credentials via: container-role
2024-01-11 03:07:22,367 - botocore.credentials - DEBUG - Looking for credentials via: iam-role
2024-01-11 03:07:22,368 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 169.254.169.254:80
2024-01-11 03:07:23,370 - botocore.utils - DEBUG - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/api/token: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
Traceback (most recent call last):
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
                      ^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/botocore/awsrequest.py", line 96, in request
    rval = super().request(method, url, body, headers, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/botocore/awsrequest.py", line 123, in _send_output
    self.send(msg)
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/botocore/awsrequest.py", line 223, in send
    return super().send(str)
           ^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x7f88cc7e5c10>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/botocore/utils.py", line 460, in _fetch_metadata_token
    response = self._session.send(request.prepare())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/botocore/httpsession.py", line 499, in send
    raise ConnectTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
2024-01-11 03:07:23,375 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): 169.254.169.254:80
2024-01-11 03:07:24,377 - botocore.utils - DEBUG - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/meta-data/iam/security-credentials/: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
Traceback (most recent call last):
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
                      ^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/botocore/awsrequest.py", line 96, in request
    rval = super().request(method, url, body, headers, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/botocore/awsrequest.py", line 123, in _send_output
    self.send(msg)
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/botocore/awsrequest.py", line 223, in send
    return super().send(str)
           ^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x7f88cc5cc890>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/botocore/utils.py", line 515, in _get_request
    response = self._session.send(request.prepare())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/botocore/httpsession.py", line 499, in send
    raise ConnectTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
2024-01-11 03:07:24,380 - botocore.utils - DEBUG - Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
2024-01-11 03:07:24,381 - botocore.loaders - DEBUG - Loading JSON file: /opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/botocore/data/endpoints.json
2024-01-11 03:07:24,396 - botocore.loaders - DEBUG - Loading JSON file: /opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/botocore/data/sdk-default-configuration.json
2024-01-11 03:07:24,397 - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f88cc718900>
2024-01-11 03:07:24,411 - botocore.loaders - DEBUG - Loading JSON file: /opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/botocore/data/s3/2006-03-01/service-2.json
2024-01-11 03:07:24,427 - botocore.loaders - DEBUG - Loading JSON file: /opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/botocore/data/s3/2006-03-01/endpoint-rule-set-1.json
2024-01-11 03:07:24,431 - botocore.loaders - DEBUG - Loading JSON file: /opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/botocore/data/partitions.json
2024-01-11 03:07:24,433 - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f88cc878e00>
2024-01-11 03:07:24,433 - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x7f88ccc20220>
2024-01-11 03:07:24,447 - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f88cc878b80>
2024-01-11 03:07:24,447 - botocore.configprovider - DEBUG - Looking for endpoint for s3 via: environment_service
2024-01-11 03:07:24,447 - botocore.configprovider - DEBUG - Looking for endpoint for s3 via: environment_global
2024-01-11 03:07:24,447 - botocore.configprovider - DEBUG - Looking for endpoint for s3 via: config_service
2024-01-11 03:07:24,447 - botocore.configprovider - DEBUG - Looking for endpoint for s3 via: config_global
2024-01-11 03:07:24,447 - botocore.configprovider - DEBUG - No configured endpoint found.
2024-01-11 03:07:24,460 - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2024-01-11 03:07:24,462 - botocore.loaders - DEBUG - Loading JSON file: /opt/conda/envs/hyp3-isce2/lib/python3.11/site-packages/botocore/data/_retry.json
2024-01-11 03:07:24,462 - botocore.client - DEBUG - Registering retry handlers for service: s3
2024-01-11 03:07:24,463 - botocore.utils - DEBUG - Registering S3 region redirector handler
2024-01-11 03:07:24,463 - botocore.utils - DEBUG - Registering S3Express Identity Resolver
2024-01-11 03:07:25,524 - hyp3_isce2.insar_tops_burst - INFO - Begin ISCE2 TopsApp run
2024-01-11 03:07:30,789 - hyp3_isce2.burst - INFO - Download attempt #1 for https://sentinel1-burst.asf.alaska.edu/S1A_IW_SLC__1SDV_20200604T022251_20200604T022318_032861_03CE65_7C85/IW2/VV/7.xml
```

</details>

**Comment by jhkennedy** [comment]
@scottyhq I agree the volume of debug output is *rather annoying* and caused by importing ISCE2 which sets the logging level to DEBUG for *everything*:
1. https://github.com/isce-framework/isce2/blob/main/__init__.py#L37-L39
2. https://github.com/isce-framework/isce2/blob/main/defaults/logging/logging.conf#L11

and I just haven't been sufficiently annoyed by it to work around/fix it yet :rofl: Happy to take PRs for that, though!

For `botocore`, I believe that call to `http://169.254.169.254/latest/api/token` is only something that will succeed *in* AWS and is expected to fail outside of it, so non-fatal. botocore is reasonably expecting you to not see the the botocore debug logs unless you're actively debugging botocore.
