### ISSUE TITLE
HTTPError: 502 Server Error: Bad Gateway for url

### ISSUE THREAD

**Issue by scottyhq** [ASFHyP3/hyp3-isce2#184]
### The bug

Running this workflow I periodically get a 502 Server Error. It seems like an intermittent server-side error since waiting a few seconds and re-running tends to work (v0.9.2)

### To Reproduce
```bash
python -m hyp3_isce2 ++process insar_tops_burst \
  S1_136231_IW2_20200604T022312_VV_7C85-BURST \
  S1_136231_IW2_20200616T022313_VV_5D11-BURST \
  --looks 20x4 \
  --apply-water-mask False
```

 ### Additional context
```pytb
/Users/scott/GitHub/relativeorbit/hyp3-isce2/src/hyp3_isce2/__main__.py:40: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  eps = entry_points()['hyp3']
2024-01-16 14:51:38,405 - hyp3_isce2.insar_tops_burst - INFO - Begin ISCE2 TopsApp run
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/scott/GitHub/relativeorbit/hyp3-isce2/src/hyp3_isce2/__main__.py", line 51, in <module>
    main()
  File "/Users/scott/GitHub/relativeorbit/hyp3-isce2/src/hyp3_isce2/__main__.py", line 47, in main
    sys.exit(process_entry_point.load()())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/GitHub/relativeorbit/hyp3-isce2/src/hyp3_isce2/insar_tops_burst.py", line 482, in main
    isce_output_dir = insar_tops_burst(
                      ^^^^^^^^^^^^^^^^^
  File "/Users/scott/GitHub/relativeorbit/hyp3-isce2/src/hyp3_isce2/insar_tops_burst.py", line 90, in insar_tops_burst
    ref_metadata, sec_metadata = download_bursts([ref_params, sec_params])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott/GitHub/relativeorbit/hyp3-isce2/src/hyp3_isce2/burst.py", line 311, in download_bursts
    with get_asf_session() as asf_session:
         ^^^^^^^^^^^^^^^^^
  File "/Users/scott/GitHub/relativeorbit/hyp3-isce2/src/hyp3_isce2/burst.py", line 290, in get_asf_session
    response.raise_for_status()
  File "/Users/scott/miniforge3/envs/hyp3-isce2/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://auth.asf.alaska.edu/login?code=xxOZZcOSRk_giCfl0AwwYCehOu5MlGZFtgDjKuhIdYBM7gXCnB2CSddBGA 

```

**Comment by scottyhq** [comment]
> It seems like an intermittent server-side error since waiting a few seconds and re-running tends to work (v0.9.2)

Actually been getting the same error for about the last hour. Same error if running wget to a burst URL ` wget https://sentinel1-burst.asf.alaska.edu/S1A_IW_SLC__1SDV_20230703T121403_20230703T121430_049259_05EC58_F9AB/IW1/VV/8.tiff` , but I am able to download a burst URL directly from the web GUI in ASF vertex. Not sure how the authentication flow is different for programmatic access...

**Comment by asjohnston-asf** [comment]
This appears related to a degraded service event for Earthdata Login: https://status.earthdata.nasa.gov/status_page/21
