### ISSUE TITLE
ValueError: ASF Search failed to find S1_023790_IW1_20230621T121426_VV_BAD8-BURST.

### ISSUE THREAD

**Issue by gbrencher** [ASFHyP3/hyp3-isce2#188]
### The bug
When running the workflow locally, I encountered this error a few times in a row. 15 minutes later I tried again and the workflow ran as expected. Now the error is back. 

### To Reproduce
`python -m hyp3_isce2 ++process insar_tops_burst   S1_023790_IW1_20231218T121430_VV_B9A6-BURST   S1_023790_IW1_20230621T121426_VV_BAD8-BURST   --looks 5x1`

 ### Additional context
`2024-01-24 14:20:57,426 - hyp3_isce2.insar_tops_burst - INFO - Begin ISCE2 TopsApp run
2024-01-24 14:21:27,543 - root - ERROR - Connection Error (Timeout): CMR took too long to respond. Set asf constant "CMR_TIMEOUT" to increase. (url='https://cmr.earthdata.nasa.gov/search/granules.umm_json', timeout=30)
2024-01-24 14:21:28,000 - root - ERROR - The asf-search module ecountered an error with CMR, and the following message was automatically reported to ASF:

"
Error Message: Connection Error (Timeout): CMR took too long to respond. Set asf constant "CMR_TIMEOUT" to increase. (url='https://cmr.earthdata.nasa.gov/search/granules.umm_json', timeout=30)
User Agent: Python/3.11.6; requests/2.31.0; asf_search/6.7.3
Search Options: {
        product_list: ['S1_023790_IW1_20230621T121426_VV_BAD8-BURST']
}
"If you have any questions email uso@asf.alaska.edu
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/mnt/c/Users/qbren/Desktop/taco/projects/hyp3-isce2/src/hyp3_isce2/__main__.py", line 51, in <module>
    main()
  File "/mnt/c/Users/qbren/Desktop/taco/projects/hyp3-isce2/src/hyp3_isce2/__main__.py", line 47, in main
    sys.exit(process_entry_point.load()())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/qbren/Desktop/taco/projects/hyp3-isce2/src/hyp3_isce2/insar_tops_burst.py", line 508, in main
    isce_output_dir = insar_tops_burst(
                      ^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/qbren/Desktop/taco/projects/hyp3-isce2/src/hyp3_isce2/insar_tops_burst.py", line 87, in insar_tops_burst
    ref_params = get_burst_params(reference_scene)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/qbren/Desktop/taco/projects/hyp3-isce2/src/hyp3_isce2/burst.py", line 373, in get_burst_params
    raise ValueError(f'ASF Search failed to find {scene_name}.')
ValueError: ASF Search failed to find S1_023790_IW1_20230621T121426_VV_BAD8-BURST.`

**Comment by forrestfwilliams** [comment]
Hey @gbrencher NASA CMR's service has been unreliable lately and it may have been down when you tried running this command. Try running it again and it should work!

**Comment by asjohnston-asf** [comment]
Closing this stale issue. The original report was most likely the result of a CMR degraded service event.
