### ISSUE TITLE
insar_tops and insar_tops_burst workflows fail to geocode z.rdr.full.vrt

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/hyp3-isce2#65]
`z.rdr.full.vrt` was added to the list of images to geocode at https://github.com/ASFHyP3/hyp3-isce2/blob/develop/src/hyp3_isce2/topsapp.py#L38

The geocoding code expects `filename + '.xml'` to exist in the same directory. For the dem, the only files in the merged directory are:
```
z.rdr.full.vrt
z.rdr.full.xml
```

So the program fails with a `No such file or directory: 'merged/z.rdr.full.vrt.xml'` exception:

```
Writing geotrans to VRT for merged/los.rdr.geo
Traceback (most recent call last):
  File "/home/asjohnston/mambaforge/envs/hyp3-isce2/bin/insar_tops", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/asjohnston/src/hyp3-isce2/src/hyp3_isce2/insar_tops.py", line 105, in main
    product_dir = insar_tops(
                  ^^^^^^^^^^^
  File "/home/asjohnston/src/hyp3-isce2/src/hyp3_isce2/insar_tops.py", line 81, in insar_tops
    topsapp.run_topsapp_burst(start='startup', end='geocode', config_xml=config_path)
  File "/home/asjohnston/src/hyp3-isce2/src/hyp3_isce2/topsapp.py", line 172, in run_topsapp_burst
    insar.run()
  File "/home/asjohnston/mambaforge/envs/hyp3-isce2/lib/python3.11/site-packages/isce/components/iscesys/Component/Application.py", line 142, in run
    exitStatus = self._processSteps()
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/asjohnston/mambaforge/envs/hyp3-isce2/lib/python3.11/site-packages/isce/components/iscesys/Component/Application.py", line 405, in _processSteps
    result = func(*pargs, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asjohnston/mambaforge/envs/hyp3-isce2/lib/python3.11/site-packages/isce/components/isceobj/TopsProc/Factories.py", line 40, in __call__
    return self.method(self.other, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asjohnston/mambaforge/envs/hyp3-isce2/lib/python3.11/site-packages/isce/components/isceobj/TopsProc/runGeocode.py", line 125, in runGeocode
    inImage,method = ge.create(prod)
                     ^^^^^^^^^^^^^^^
  File "/home/asjohnston/mambaforge/envs/hyp3-isce2/lib/python3.11/site-packages/isce/components/stdproc/rectify/geocode/Geocodable.py", line 62, in create
    prop, fac, misc = parser.parse(filename + '.xml')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asjohnston/mambaforge/envs/hyp3-isce2/lib/python3.11/site-packages/isce/components/iscesys/Parsers/XmlParser.py", line 41, in parse
    root = ET.parse(filename)
           ^^^^^^^^^^^^^^^^^^
  File "/home/asjohnston/mambaforge/envs/hyp3-isce2/lib/python3.11/xml/etree/ElementTree.py", line 1218, in parse
    tree.parse(source, parser)
  File "/home/asjohnston/mambaforge/envs/hyp3-isce2/lib/python3.11/xml/etree/ElementTree.py", line 569, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'merged/z.rdr.full.vrt.xml'
```

**Comment by asjohnston-asf** [comment]
The `insar_tops_burst` workflow addresses this by renaming the xml file: https://github.com/ASFHyP3/hyp3-isce2/blob/develop/src/hyp3_isce2/insar_tops_burst.py#L107
